quarkus.http.port=6060
quarkus.http.test-port=6061

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PATCH,PUT,DELETE
quarkus.http.cors.headers=accept,origin,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Content-Type,Authorization

quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=1234

quarkus.mongodb.connection-string=mongodb://admin:1234@localhost:27018
quarkus.mongodb.database=user
