# port setting
quarkus.http.port=6060
quarkus.http.test-port=6061

# cors setting
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PATCH,PUT,DELETE
quarkus.http.cors.headers=accept,origin,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=Content-Type,Authorization

# Redis setting
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=1234

# MySQL reactive setting
quarkus.datasource.reactive.url=mysql://localhost:3306/ticketing
quarkus.datasource.username=appuser
quarkus.datasource.password=apppw
quarkus.datasource.db-kind=mysql

# MySQL JDBC setting
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# MongoDB setting(use MySQL for now)
#quarkus.mongodb.connection-string=mongodb://admin:1234@localhost:27018
#quarkus.mongodb.database=user

# JWT Token setting
quarkus.smallrye-jwt.enabled=true

#note: is 'publickey', not 'publicKey'
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ticketing-app

smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.signature-algorithm=RS256


